### PR TITLE
page preview functionality

### PR DESCRIPTION
**Pull request by barrust**
simulate pulling a page preview using the standard `mediawiki api`

### CODE REVIEW

**Comment by barrust** [comment]
@luni3359 how does this look? Thanks!

**Comment by luni3359** [comment]
It looks pretty nice! I didn't know the api could already do that by itself. I have a question, does this return a binary blob with the image or just an url to it? I'm assuming the latter and that's what I think would work best, too.

**Comment by barrust** [comment]
It returns the url. For example this is the output for "Dog":

``` bash
{
    "title": "Dog",
    "ns": 0,
    "pagelanguage": "en",
    "contentmodel": "wikitext",
    "pageid": 4269567,
    "length": 110533,
    "pagelanguagedir": "ltr",
    "terms": {
        "description": [
            "domestic animal"
        ]
    },
    "revisions": [
        {
            "parentid": 1060379686,
            "revid": 1061138883,
            "timestamp": "2021-12-19T22:08:52Z"
        }
    ],
    "pagelanguagehtmlcode": "en",
    "extract": "The dog or domestic dog, (Canis familiaris or Canis lupus familiaris) is a domesticated descendant of the wolf which is characterized by an upturning tail. The dog derived from an ancient, extinct wolf, and the modern grey wolf is the dog's nearest living relative. The dog was the first species to be domesticated, by hunter–gatherers over 15,000 years ago, before the development of agriculture.Due to their long association with humans, dogs have expanded to a large number of domestic individuals and gained the ability to thrive on a starch-rich diet that would be inadequate for other canids. Over the millennia, dogs became uniquely adapted to human behavior, and the human-canine bond has been a topic of frequent study.The dog has been selectively bred over millennia for various behaviors, sensory capabilities, and physical attributes. Dog breeds vary widely in shape, size, and color.",
    "touched": "2021-12-21T22:21:36Z",
    "lastrevid": 1061138883
}

```

**Comment by luni3359** [comment]
It seems like the Dog article doesn't have any specific preview images to show by default. I was thinking about how Wikipedia decides what should be taken as the preview of their articles in other sites, like on Discord:
Discord screenshot

Do you think you could show me what the json looks like on the Culture page?

**Comment by barrust** [comment]
``` bash
{
    "length": 68862,
    "revisions": [
        {
            "timestamp": "2021-12-19T09:16:20Z",
            "parentid": 1061014203,
            "revid": 1061047761
        }
    ],
    "extract": "Culture () is an umbrella term which encompasses the social behavior and norms found in human societies, as well as the knowledge, beliefs, arts, laws, customs, capabilities, and habits of the individuals in these groups.Humans acquire culture through the learning processes of enculturation and socialization, which is shown by the diversity of cultures across societies.\nA cultural norm codifies acceptable conduct in society; it serves as a guideline for behavior, dress, language, and demeanor in a situation, which serves as a template for expectations in a social group.\nAccepting only a monoculture in a social group can bear risks, just as a single species can wither in the face of environmental change, for lack of functional responses to the change. \nThus in military culture, valor is counted a typical behavior for an individual and duty, honor, and loyalty to the social group are counted as virtues or functional responses in the continuum of conflict. In the practice of religion, analogous attributes can be identified in a social group.",
    "ns": 0,
    "lastrevid": 1061047761,
    "touched": "2021-12-23T16:14:09Z",
    "contentmodel": "wikitext",
    "original": {
        "height": 789,
        "source": "https://upload.wikimedia.org/wikipedia/commons/8/8b/9_Bisonte_Magdaleniense_pol%C3%ADcromo.jpg",
        "width": 1181
    },
    "thumbnail": {
        "height": 214,
        "source": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/9_Bisonte_Magdaleniense_pol%C3%ADcromo.jpg/320px-9_Bisonte_Magdaleniense_pol%C3%ADcromo.jpg",
        "width": 320
    },
    "terms": {
        "description": [
            "society's way of life within anthropology"
        ]
    },
    "pageid": 19159508,
    "pagelanguagehtmlcode": "en",
    "pagelanguage": "en",
    "pagelanguagedir": "ltr",
    "title": "Culture"
}
```

**Comment by luni3359** [comment]
Perfect! The only concern I would have with it is that since not all articles have image previews it could get confusing for other users of mediawiki, but it's easily solvable by checking whether or not "original" or "thumbnail" exist in the object.

**Comment by barrust** [comment]
So this is how the data comes directly from the api. It could be cleaned to be standardized in all instances. We could also remove some of the less relevant items. Thoughts?

**Comment by luni3359** [comment]
As long as we keep the elements that make up Wikipedia's hover preview it should be fine in my opinion. What elements do you think are not as relevant?

**Pull request merged**
