### PR TITLE
Allow parsing links in the first part of a page, between the main title and the first section.

### PR DESCRIPTION
**Pull request by ldorigo**
I'm not sure about what the best argument would be to `parse_section_titles` - for now, it downloads the first section if a `0` is passed to it. I also changed the inline documentation. If you have other suggestions, I'm open.

### CODE REVIEW

**Comment by ldorigo** [comment]
(note that this comes after the other pull request I submitted)

**Comment by barrust** [comment]
A few thoughts:
1) Thank you for the idea to cache the `BeautifulSoup` results! I have merged that and have added the remaining 2 or 3 places where it could be done. 
2) There is now (prior to my additional work) a merge conflict here. Would you like to address it or should I look into replicating what you pulled together? 
3) Thinking about the use of `0` to indicate the unnamed section, I think I would prefer using `None` as it could simplify some of the logic. Thoughts? 

I would like to fix and merge this PR (or another one just like it) so that I can build a new release that will likely be the last version to support python 2.7 as it will go away as a testable option in January. 

Thanks for your help!

**Comment by ldorigo** [comment]
Hi @barrust , sorry I haven't been responsive - I made those two pull requests because I needed this library as part of an assignment, and have been too busy with said assignment to respond to your comments. 

I remember considering `None` as a parameter for the header section, and I remember choosing against it, but I really cannot remember why right now... If it works, then I'm fine with None!

Thanks for fixing and merging my PR's !

Luca

**Comment by barrust** [comment]
Closing as #94 resolves this!

**Pull request closed without merging**
